# Case Study Submission:
# Numpy Case Study 2 - Student: Ginju Soumya

Libraries and Modules: Import

In [2]:
import numpy as np
from numpy.random import random as rand
from numpy.random import randint as ri

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [15]:
mat1 = np.arange(1,10).reshape(3,3)
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
mat2 = np.array(ri(1,9,9)).reshape(3,3)
mat2 

array([[7, 3, 7],
       [8, 4, 2],
       [4, 2, 8]])

In [17]:
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


1st Matrix of random single-digit numbers
----------------------------------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[7 3 7]
 [8 4 2]
 [4 2 8]]


In [18]:
print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


Addition
------------------
 [[ 8  5 10]
 [12  9  8]
 [11 10 17]]

Multiplication
------------------
 [[ 7  6 21]
 [32 20 12]
 [28 16 72]]


In [21]:
print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


Division
------------------
 [[0.14285714 0.66666667 0.42857143]
 [0.5        1.25       3.        ]
 [1.75       4.         1.125     ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-11   0  -5]
 [ -4   7  14]
 [ 13  20  11]]


In [22]:
print("\nAddition of a scalar (100)\n-------------------------\n", mat1+100)


Addition of a scalar (100)
-------------------------
 [[101 102 103]
 [104 105 106]
 [107 108 109]]


In [23]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n", mat1**0.5)


Exponentiation, matrix cubed here
----------------------------------------
 [[  1   8  27]
 [ 64 125 216]
 [343 512 729]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [24]:
mat1 = np.arange(1,10).reshape(3,3)
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
mat2 = np.array(ri(1,9,9)).reshape(3,3)
mat2 

array([[4, 5, 5],
       [7, 8, 2],
       [6, 3, 1]])

In [26]:
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[4 5 5]
 [7 8 2]
 [6 3 1]]


In [29]:
print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))


Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 45

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [ 6 15 24]


In [30]:
print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1, axis=0))


Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [12 15 18]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 28  80 162]


In [33]:
print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2, axis=1))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [100 112  18]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.0


In [34]:
print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2.581988897471611


In [35]:
mat1 = np.array(ri(1,100,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


Modified matrix of random numbers from 1 to 99
 -------------------------------------------------- 
 [[10 19 52]
 [94 61 42]
 [63  9 42]]


In [38]:
print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


Standard deviation of all numbers in the modified matrix, a larger number
 -------------------------------------------------------------------------------- 
 26.30213810958726


In [39]:
print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


Variance of all numbers in the modified matrix, a larger number
 -------------------------------------------------------------------------------- 
 691.8024691358025


In [40]:
print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))


Median of all numbers in the modified matrix
 ------------------------------------------------------------ 
 42.0


###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [ ]:
##Solution

In [45]:
# 3 * 3 Matrix 
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat1

array([[5, 1, 5],
       [7, 2, 6],
       [9, 9, 7]])

In [46]:
#Modify its shape to 9*1 matrix
maat1= np.sort(mat1.reshape(9,1))
maat1

array([[5],
       [1],
       [5],
       [7],
       [2],
       [6],
       [9],
       [9],
       [7]])

### 4.Sort

In [47]:
A = np.array(ri(1,100,10)) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [ 5 52 51 31 18 70 36 58 31 55]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5 18 31 31 36 51 52 55 58 70]


In [48]:
M = np.random.randint(1,100,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis=0)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=1))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[72 15 62 83 56]
 [35 60 19 20 10]
 [95 87 24 40 93]
 [53 60 31 16  5]
 [68 77 76 95 97]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[35 15 19 16  5]
 [53 60 24 20 10]
 [68 60 31 40 56]
 [72 77 62 83 93]
 [95 87 76 95 97]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[15 56 62 72 83]
 [10 19 20 35 60]
 [24 40 87 93 95]
 [ 5 16 31 53 60]
 [68 76 77 95 97]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [49]:
# Fill the following ***** with appropriate solution.
a=np.array(ri(1,100,10))
b=np.array(ri(1,100,10))
c=np.array(ri(1,100,10))

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.max(a))
print("Max of b:", np.max(b))


print("Max of a location:", (np.argmax(a)))
print("Max of b location:", (np.argmax(b)))
print("Max of c location:", (np.argmax(c)))

### below codes looks like reduandant
##print("Max of a:", *****)
##print("Max of b:", ****)


##print("Max of a location:", ******)
##print("Max of b location:", ******)
##print("Max of c location:", ******)



a: [99 26 80 65 15  7 55  4 96 69]
b: [36 82 51 89 59 53 35 21 68 51]
c: [ 3 93 18 91 70 22 54 98 38 12]
Max of a: 99
Max of b: 89
Max of a location: 0
Max of b location: 3
Max of c location: 7


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [3]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat1

array([[2, 4, 8],
       [2, 2, 6],
       [6, 1, 8]])

In [4]:
mat2 = np.array(ri(0,9,9).reshape(3,3))
mat2 

array([[2, 7, 2],
       [6, 7, 3],
       [1, 1, 4]])

In [5]:
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


1st Matrix of random single-digit numbers
----------------------------------------
 [[2 4 8]
 [2 2 6]
 [6 1 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[2 7 2]
 [6 7 3]
 [1 1 4]]


In [6]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


Sq-root of 1st matrix using np
------------------
 [[1.41421356 2.         2.82842712]
 [1.41421356 1.41421356 2.44948974]
 [2.44948974 1.         2.82842712]]


In [7]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[7.38905610e+00 5.45981500e+01 2.98095799e+03]
 [7.38905610e+00 7.38905610e+00 4.03428793e+02]
 [4.03428793e+02 2.71828183e+00 2.98095799e+03]]


In [8]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log(mat1))


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.69314718 1.38629436 2.07944154]
 [0.69314718 0.69314718 1.79175947]
 [1.79175947 0.         2.07944154]]


In [9]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.remainder(mat1,mat2))


Modulo reminder using np
 -------------------------------------------------- 
 [[0 4 0]
 [2 2 0]
 [0 0 0]]


### 7.Generating matrices from distributions

In [56]:
print("Random number generation (from Uniform distribution)")
print(np.array(rand(6)).reshape(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,10).reshape((5,2))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.05792663 0.8822496  0.79130607]
 [0.34514943 0.47583032 0.7564829 ]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-1.15117685 -2.36297769  0.05598539]
 [-0.39613825  0.34056313  0.32222928]
 [ 0.52313652  0.47965743 -1.57287539]
 [-0.02591057 -1.51691813 -1.08561266]]
Random integer vector: [79 60 64 47 85 44 39 60 56 39]

Random integer matrix
[[98 72]
 [12 48]
 [56 91]
 [92 56]
 [26 26]]

20 samples drawn from a dice throw: [6 6 1 5 1 5 4 2 5 1 1 5 3 2 1 4 4 1 6 5]


### 8.Find the nearest value from a given number in an array using NumPy.

In [ ]:
# to check

In [57]:
rand_array=np.array(ri(1,12,5))
print(rand_array)
rand_array[rand_array.argmax()]

[ 8  6  3  7 10]


10

### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [58]:
array_numpy = np.array([[0, 0, 0], [0, 1, 2], [0, 2, 4]])
print(array_numpy)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


# The End

# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.